<a href='https://ai.meng.duke.edu'> = <img align="left" style="padding-top:10px;" src=https://storage.googleapis.com/aipi_datasets/Duke-AIPI-Logo.png>

# Introduction to NumPy

In [1]:
import numpy as np

### Create a NumPy ndarray

In [2]:
# Method 1: from a Python list
x_array = np.array([4.25, 3, 4, 5])
print('x_array is: ',x_array)

# Method 2: from scratch
y_array = np.ones(3, dtype=int)
print('y_array is: ',y_array)

# Create a multidimensional array
z_array = np.array([[2,3,4],[4,5,6],[7,8,9],[10,11,12]])
print('z_array is: \n',z_array)

x_array is:  [4.25 3.   4.   5.  ]
y_array is:  [1 1 1]
z_array is: 
 [[ 2  3  4]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [69]:
# Convert an array back to a list
x_array = np.array([4.25, 3, 4, 5])
x_list = x_array.tolist()
x_list

[4.25, 3.0, 4.0, 5.0]

### Reshaping arrays

In [3]:
# Check the shape of an array
z_array.shape

(4, 3)

In [4]:
# Reshape the array by specifying the length of the dimensions we want
z_reshaped = z_array.reshape((6,2))
z_reshaped

array([[ 2,  3],
       [ 4,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

Sometimes we need to add extra dimensions to an array or remove an empty dimension in order for it to be used as an input to a function or model.

In [5]:
# Add an extra dimension to an array
z_reshaped = np.expand_dims(z_reshaped,axis=2)
z_reshaped.shape

(6, 2, 1)

In [6]:
# Remove a dimension which is empty (in this case, the 3rd dimension of our z_reshaped array)
z_reshaped = z_reshaped.squeeze()
z_reshaped.shape

(6, 2)

### Slicing arrays

In [12]:
# Retrieve an element of an array using its index value
x = np.array([1,2,3,4])
x[1]

2

In [13]:
# Retrieve a slice of an array
x[0:3:2] # Use start:stop:step (if you leave step out it is assumed to be 1)

array([1, 3])

In [47]:
# Can also use this technique to reverse an array by using step = -1
x[::-1]

[4, 3, 2, 1]

In [11]:
# Retrieve an element of an array using its index values
x = np.array([[1,2],[3,4]])
x[1,0]

3

In [16]:
# Retrieve a multi-dimensional slice
z_array = np.array([[2,3,4],[4,5,6],[7,8,9],[10,11,12]])
z_array[0:3,2]

array([4, 6, 9])

### Concatenating arrays

In [48]:
x = [[1,2],[3,4]]
y = [[5,6],[7,8]]

# Concatenate by adding the arrays together as rows (axis 0)
xy1 = np.concatenate([x,y],axis=0)
print('xy1: \n',xy1)

# Concatenate by adding the arrays together as columns (axis 1)
xy2 = np.concatenate([x,y],axis=1)
print('xy2: \n',xy2)

xy1: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
xy2: 
 [[1 2 5 6]
 [3 4 7 8]]


### Aggregations

In [51]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('x: \n',x)

# Compute the sum of rows, columns and the array
print('Sums of rows are: \n', np.sum(x, axis=1)) # Sum all columns for each row
print('Sums of columns are: \n', np.sum(x, axis=0)) # Sum all rows for each column
print('Sum of the full array is: \n', np.sum(x)) # Sum the full array

x: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sums of rows are: 
 [ 6 15 24]
Sums of columns are: 
 [12 15 18]
Sum of the full array is: 
 45


### Statistics

In [54]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('x: \n',x)

# Compute mean, min, max for each row
print('Max of rows are: ', np.max(x,axis=1))
print('Min of rows are: ', np.min(x,axis=1))
print('Means of rows are: ', np.mean(x,axis=1))

# Compute mean, min, max for each column
print('Max of rows are: ', np.max(x,axis=0))
print('Min of rows are: ', np.min(x,axis=0))
print('Means of rows are: ', np.mean(x,axis=0))

x: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Max of rows are:  [3 6 9]
Min of rows are:  [1 4 7]
Means of rows are:  [2. 5. 8.]
Max of rows are:  [7 8 9]
Min of rows are:  [1 2 3]
Means of rows are:  [4. 5. 6.]


In [30]:
# Get the index of the maximum value in a vector
x = np.array([2,4,1,7,5])
print(f'Index of the maximum value is {np.argmax(x)}')
print(f'Index of the minimum value is {np.argmin(x)}')

Index of the maximum value is 3
Index of the minimum value is 2


### Unique values and counts of values
You can use `np.unique(array_name)` to get the unique values in an array.  You can also use `np.unique(array_name,return_counts=True)` to return the unique values in row 0 and the count of each contained in row 1.

In [19]:
x = np.array([3,1,6,2,3,3,1,5,6])
print(f'Unique values are {np.unique(x)}')

Unique values are [1 2 3 5 6]
Unique values and counts are (array([1, 2, 3, 5, 6]), array([2, 1, 3, 1, 2]))


In [21]:
x = np.array([3,1,6,2,3,3,1,5,6])
print(f'Unique values are {np.unique(x,return_counts=True)[0]}')
print(f'Counts of each unique value are {np.unique(x,return_counts=True)[1]}')

Unique values are [1 2 3 5 6]
Counts of each unique value are [2 1 3 1 2]


### Operations via Broadcasting

Operations on arrays can be performed using Python's standard operators, and are vectorized for much quicker calculation than loops

In [66]:
x = np.array([1,2,3])
print('x = ', x)
print('x+5 = ', x+5)
print('x*5 = ', x*5)

x =  [1 2 3]
x+5 =  [6 7 8]
x*5 =  [ 5 10 15]


In [65]:
print('ln(x) = ',np.log(x))
print('e^x = ',np.exp(x))

ln(x) =  [0.         0.69314718 1.09861229]
e^x =  [ 2.71828183  7.3890561  20.08553692]


### Comparisons & filtering arrays with Boolean masks

Comparison operators can be used on arrays to return Boolean (True/False) values. These Boolean values can then be used as a “mask” to filter arrays

In [76]:
x = np.array([1,2,3,4])
# Use comparison operators to return an array of Boolean values
print('x: ',x)
print('x>2: ',x>2)
print('x==4: ',x == 4)
print('x!=2: ',x!=2)

x:  [1 2 3 4]
x>2:  [False False  True  True]
x==4:  [False False False  True]
x!=2:  [ True False  True  True]


In [79]:
# The returned Boolean array can be used as a "mask" or filter on the original array
print(x[x>2]) # Returns all elements of x where x>2
print(x[x!=2]) # Returns all elements of x where x is not equal to 2

[3 4]
[1 3 4]


In [65]:
# You can also use the returned Boolean array as a "mask" or filter on another array
x = np.array([1,2,3,4])
y = np.array([10,20,30,40])
print(x>2) # Positions where the condition is true ("mask")
print(y[x>2]) # Returns all elements of y matching the positions where the condition is true

[False False  True  True]
[30 40]


In [55]:
# You can combine multiple conditions using bitwise Boolean operators (e.g. &,|)
x = np.array([1,2,3,4])
print(x[(x>2) & (x!=4)])

[3]


In [68]:
# You can get the indices which filter an array using a comparision operator
x = np.array([1,2,3,4])
print('x: \n',x)
idxs = np.argwhere(x>2)
print(f'Indices where x>2: {idxs}')

x: 
 [1 2 3 4]
Indices where x>2: [[2]
 [3]]


### Sorting arrays

You can sort arrays and return either the sorted values or the indices of the sorted values

In [22]:
x = np.array([[3,1,6],[5,0,3]])
print('x: \n',x)

# Sort the array's rows
y = np.sort(x, axis=1) # Sort on axis 1 (across)
print('Sorted rows: \n',y)

# Sort the array's columns
z = np.sort(x, axis=0) # Sort on axis 0 (down)
print('Sorted rows: \n',z)

x: 
 [[3 1 6]
 [5 0 3]]
Sorted rows: 
 [[1 3 6]
 [0 3 5]]
Sorted rows: 
 [[3 0 3]
 [5 1 6]]


In [23]:
# Return the sorted array's indices
rowsort_indices = np.argsort(x, axis=1) # Return indices from sorting on axis 1 (across)
print('Sorted row indices: \n',rowsort_indices)

colsort_indices = np.argsort(x, axis=0) # Return indices from sorting on axis 0 (down)
print('Sorted row indices: \n',colsort_indices)

Sorted row indices: 
 [[1 0 2]
 [1 2 0]]
Sorted row indices: 
 [[0 1 1]
 [1 0 0]]
